name: Map update

on:
  push:
    branches:
      - main
    paths:
      - 'data/data.tsv'

jobs:
  my-job-name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib cartopy folium selenium pillow

    - name: Setup ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        sudo apt-get install default-jdk # for selenium server
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run map visualization script
      run: |
        xvfb-run python scripts/map.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://${{secrets.MAP_METAGENOME}}@github.com/Gevika/map_metagenome.git
        git add README.md images/map_image.png index.html
        git commit -m "Update map visualization in README.md"
        git push
